version: '3.1'

services:

    proxy_nginx:
        container_name: proxy
        build: "./nginx"
        restart: always
        ports: 
            - "80:80"
        links: 
            - api
    
    hivemq:
        container_name: broker
        build: "./hivemq"
        restart: always
        #ports: 
        #    - "8080:8080"
        links: 
            - api

    api:
        container_name: api
        build: "./api"
        restart: always
        #ports:
        #   - "3000:3000"
        depends_on: 
            - mongo
        environment:
            - PORT=3000
            - MONGO_USER=msavila
            - MONGO_PASS=msavila
            - MONGO_HOST=mongo:27017
            - MONGO_DBAS=admin
            - MQ_USER=msavila-api
            - MQ_PASS=msavila-pass 
            - MQ_HOST=hivemq:1883
    
    app:
        container_name: app
        build: "./app"
        restart: always
        #ports:
        #    - 4200:80
        depends_on: 
            - api

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes: 
            - "db-data:/data/db"
        #ports:
        #   - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: msavila
            MONGO_INITDB_ROOT_PASSWORD: msavila

    mongo-express:
        container_name: mongo-admin
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: msavila
            ME_CONFIG_MONGODB_ADMINPASSWORD: msavila
            ME_CONFIG_MONGODB_URL: mongodb://msavila:msavila@mongo:27017/

volumes:
        db-data: