CODE_PET = 1658540672

WIFI_NETWORK = "Maicol"
WIFI_PASSWORD = "1007719431"

MQTT_CLIENT_ID = "esp32-michael-1"
MQTT_BROKER = "134.122.8.119"
MQTT_USER = "msavila_esp"
MQTT_PASSWORD = "msavila_pwd_esp"
MQTT_TOPIC_CONFIGS = "iot/configs"
MQTT_TOPIC_TRACK = "iot/track"

GPS_UART_N = 2
GPS_UART_BAUDRATE = 9600

PIN_LED_RED = 14
PIN_LED_GREEN = 27
PIN_LED_BLUE = 26
TIMER_N_RED = 1
TIMER_N_GREEN = 2
TIMER_N_BLUE = 3
BLINK_TIME_MS = 200

TIMER_N = 0
TIMER_CONFIGS_URL = "http://134.122.8.119/api/configs"
DATA_FIELD = "data"
DO_SYNC_FIELD = "doSync"
INTERVAL_SYNC_FIELD = "intervalSync"
CODE_PET_FIELD = "codePet"
LAT_FIELD = "lat"
LON_FIELD = "lon"
